const Descriptions = {
        Profile: "Welcome to my profile! My name is Madeline and I'm a Computer Science student at Wayne State University in Detroit, MI! I'm passionate about using technology to solve real-world problems, and I'm excited to share my skills with the right opportunity. Feel free to check out the rest of my site to learn more about the projects I'm working on!",
        Portfolio: "I started building this site to showcase some of my favorite projects. I really enjoy what I do, so I wanted to highlight my work with a fun, social-media-influenced design. While I'm still uploading content across the site, I'm so proud to see my vision coming to life! Tech stack: Django backend, React frontend, Axios and Django REST Framework for the API, Bootstrap.",
        Mobile: "Low Pressure is an app that tracks barometric pressure data and predicts weather conditions that may cause sinus headaches in individuals sensitive to changes in atmospheric pressure. I created this app to use for myself, because I suspected that my headaches were related to barometric pressure changes, but I wasn't sure which ones. I'm currently working on completing the UI, and have begun tracking the data to make predictions! Tech stack: Django, React Native, MySQL, Django REST Framework, Axios, Expo.",
        Robotics: "My robotics project isn't quite ready yet - check back soon!",
        Dsml: "This summer, right before I was supposed to fly to Alaska on a family vacation, a major earthquake hit the state. I started researching earthquakes in Alaska, and I was surprised to find that Alaska is home to major seismic activity! Inspired by this research and my trip to the state, I decided to put together a data science project on these earthquakes over the past 6 years. I look at factors like depth and magnitude, and try to predict future earthquakes based on timing and location. Currently in-progress, but I'll be making updates here! All data taken from the Alaska Earthquake Center at University of Alaska, Fairbanks."

    }

export default Descriptions;
