# Generated by Django 5.2 on 2025-08-06 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('project', models.CharField(max_length=255)),
                ('tech_stack', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('project', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('highlighted', models.TextField(default='id')),
                ('language', models.CharField(default='text')),
                ('code', models.TextField()),
                ('style', models.CharField(default='friendly')),
                ('linenos', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True)),
                ('owner', models.ForeignKey(default='mbartley', on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
