# Generated by Django 5.2 on 2025-08-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('project', models.CharField(max_length=255)),
                ('tech_stack', models.CharField(max_length=2000)),
            ],
        ),
    ]
